site_name: Wuuuk's Blog

site_url: https://wu-uk.github.io/wuuuk

repo_url: https://github.com/wu-uk/wuuuk

nav:
  - 首页: 'index.md'
  - 算法竞赛:
    - index: CP/index.md
    - 算法模板:
      - index: CP/templates/index.md
      - 数论: CP/templates/数论.md
      - 组合数学: CP/templates/组合数学.md
      - 线性代数: CP/templates/线性代数.md
      - 多项式: CP/templates/多项式.md
      - 几何: CP/templates/几何.md
      - 图论: CP/templates/图论.md
      - 数论: CP/templates/树论.md
      - 数据结构: CP/templates/数据结构.md
      - 字符串: CP/templates/字符串.md
      - 动态规划: CP/templates/动态规划.md
      - 杂项: CP/templates/杂项.md
  - 课程:
    - index: course/index.md
    - 数据结构:
      - index: course/DataStructure/index.md
      - 第一章作业: course/DataStructure/数据结构第一章作业.md
      - 第二章作业: course/DataStructure/数据结构第二章作业.md
      - 第二章实验: course/DataStructure/数据结构第二章实验.md
      - 第三章作业: course/DataStructure/数据结构第三章作业.md
      - 第三章实验1: course/DataStructure/数据结构第三章实验1.md
      - 第三章实验2: course/DataStructure/数据结构第三章实验2.md
      - 第四章作业: course/DataStructure/数据结构第四章作业.md
      - 第五章作业: course/DataStructure/数据结构第五章作业.md
      - 第五章实验报告: course/DataStructure/数据结构第五章实验报告.md
      - 第六章作业: course/DataStructure/数据结构第六章作业.md
      - 第六章实验1: course/DataStructure/数据结构第六章实验1.md
      - 第六章实验2: course/DataStructure/数据结构第六章实验2.md
      - 第七章作业: course/DataStructure/数据结构第七章作业.md
      - 第七章实验: course/DataStructure/数据结构第七章实验.md
      - 第八章作业: course/DataStructure/数据结构第八章作业.md
      - 第九章作业: course/DataStructure/数据结构第九章作业.md
      - 第十章作业: course/DataStructure/数据结构第十章作业.md
    - 计算机网络:
      - index: course/ComputerNetwork/index.md
      - 第二次作业: course/ComputerNetwork/计算机网络第二次作业.md
      - 第三次作业: course/ComputerNetwork/计算机网络第三次作业.md
      - 第四次作业: course/ComputerNetwork/计算机网络第四次作业.md
      - 第五次作业: course/ComputerNetwork/计算机网络第五次作业.md
      - 第六次作业: course/ComputerNetwork/计算机网络第六次作业.md
      - 第七次作业: course/ComputerNetwork/计算机网络第七次作业.md
      - 第八次作业: course/ComputerNetwork/计算机网络第八次作业.md
    - 操作系统:
      - index: course/OperatingSystem/index.md
      - 第一次实验-进程遍历: course/OperatingSystem/操作系统第一次实验.md
  - 项目:
    - index: project/index.md
    - LuoguAgent:
      - index: project/LuoguAgent/index.md
      - 爬虫: project/LuoguAgent/爬虫.md
      - Agent: project/LuoguAgent/agent.md
      - 前端: project/LuoguAgent/streamlit.md

markdown_extensions:
  # 启用公式支持
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

# 如果你使用的是 Material 主题，需要额外添加以下配置
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: material
  
  icon:
    logo: material/github

  language: zh

  palette:

    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: grey
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - serach.hightlight
    - content.tabs.link

copyright: Copyright &copy; 2023 - 2025 Wuuuk | wuyukai@bupt.edu.cn

extra:
  social:
    - icon: fontawesome/solid/envelope  # 使用 FontAwesome 的信封图标
      link: mailto:wuyukai@bupt.edu.cn

